name: Run Laravel Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, intl, pdo_sqlite
          coverage: xdebug

      # Install composer dependencies
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      # Setup .env for testing
      - name: Setup environment
        run: |
          cp .env.example .env
          echo "APP_ENV=testing" >> .env
          echo "APP_KEY=base64:$(php artisan key:generate --show)" >> .env
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=:memory:" >> .env
          echo "SESSION_DRIVER=array" >> .env

      # Run migrations and seeders if needed
      - name: Run migrations
        run: php artisan migrate --force

      # Run Pest tests
      - name: Run Pest tests
        run: vendor/bin/pest --coverage
